### ISSUE TITLE
不知道为啥我电脑上搜出来还是有百家号

### ISSUE THREAD

**Issue by lg10melody** [LuRenJiasWorld/Baijiahao-Fucker#1]
搜例图中翟志刚分手的那个新闻，百家号还是会有，但搜索结果第一页不满20条了，我猜可能是屏蔽一部分了？而且搜索结果显示检索到多少多少条旁边也没有显示已屏蔽百家号多少多少条的字样

**Comment by LuRenJiasWorld** [comment]
你好，方便提供下以下信息吗，我这边好复现：
- 操作系统版本
- 浏览器版本
- 油猴插件版本
- 请求地址

**Comment by LuRenJiasWorld** [comment]
已知Chrome72会出现油猴无法获取权限，报错『Limited runtime host permissions might break some Tampermonkey features like script update, GM_xmlhttpRequest and others!』的情况，详情请见https://community.brave.com/t/limited-runtime-host-permissions-for-extensions-tampermonkey/44413  https://github.com/Tampermonkey/tampermonkey/issues/640 ，如果出现问题，目前的解决方案之一是降低浏览器版本，安装测试版本油猴，或者等待油猴正式版修复该BUG。

**Comment by LuRenJiasWorld** [comment]
你也可以安装油猴的最新测试版本 https://chrome.google.com/webstore/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf 解决该问题。
此外，油猴最新版对于安全策略也有更新，因此我修改了脚本中一部分内容，请更新到最新脚本。
https://github.com/LuRenJiasWorld/Baijiahao-Fucker/commit/38504d35406f12287296455d838148d80d8c8307
谢谢支持。

**Comment by lg10melody** [comment]
> 已知Chrome72会出现油猴无法获取权限，报错『Limited runtime host permissions might break some Tampermonkey features like script update, GM_xmlhttpRequest and others!』的情况，详情请见https://community.brave.com/t/limited-runtime-host-permissions-for-extensions-tampermonkey/44413 [Tampermonkey/tampermonkey#640](https://github.com/Tampermonkey/tampermonkey/issues/640) ，如果出现问题，目前的解决方案之一是降低浏览器版本，安装测试版本油猴，或者等待油猴正式版修复该BUG。

操作系统版本：Windows10家庭中文版，基于64位操作系统
浏览器版本：360极速浏览器9.5
油猴版本：v4.7
操作系统不知道怎么查额

降低浏览器版本指的是Chrome吗？

**Comment by lg10melody** [comment]
> 已知Chrome72会出现油猴无法获取权限，报错『Limited runtime host permissions might break some Tampermonkey features like script update, GM_xmlhttpRequest and others!』的情况，详情请见https://community.brave.com/t/limited-runtime-host-permissions-for-extensions-tampermonkey/44413 [Tampermonkey/tampermonkey#640](https://github.com/Tampermonkey/tampermonkey/issues/640) ，如果出现问题，目前的解决方案之一是降低浏览器版本，安装测试版本油猴，或者等待油猴正式版修复该BUG。

操作系统版本：Windows10家庭中文版，基于64位操作系统
浏览器版本：360极速浏览器9.5
油猴版本：v4.7
操作系统不知道怎么查额

降低浏览器版本指的是Chrome吗？

> 你也可以安装油猴的最新测试版本 https://chrome.google.com/webstore/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf 解决该问题。
> 此外，油猴最新版对于安全策略也有更新，因此我修改了脚本中一部分内容，请更新到最新脚本。
> [38504d3](https://github.com/LuRenJiasWorld/Baijiahao-Fucker/commit/38504d35406f12287296455d838148d80d8c8307)
> 谢谢支持。

蟹蟹我试试

**Comment by LuRenJiasWorld** [comment]
> > 已知Chrome72会出现油猴无法获取权限，报错『Limited runtime host permissions might break some Tampermonkey features like script update, GM_xmlhttpRequest and others!』的情况，详情请见https://community.brave.com/t/limited-runtime-host-permissions-for-extensions-tampermonkey/44413 [Tampermonkey/tampermonkey#640](https://github.com/Tampermonkey/tampermonkey/issues/640) ，如果出现问题，目前的解决方案之一是降低浏览器版本，安装测试版本油猴，或者等待油猴正式版修复该BUG。
> 
> 操作系统版本：Windows10家庭中文版，基于64位操作系统
> 浏览器版本：360极速浏览器9.5
> 油猴版本：v4.7
> 操作系统不知道怎么查额
> 
> 降低浏览器版本指的是Chrome吗？
> 
> > 你也可以安装油猴的最新测试版本 https://chrome.google.com/webstore/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf 解决该问题。
> > 此外，油猴最新版对于安全策略也有更新，因此我修改了脚本中一部分内容，请更新到最新脚本。
> > [38504d3](https://github.com/LuRenJiasWorld/Baijiahao-Fucker/commit/38504d35406f12287296455d838148d80d8c8307)
> > 谢谢支持。
> 
> 蟹蟹我试试

好，如果还问题麻烦继续反馈。
安装最新脚本+测试版油猴，经测试已经没有上述问题
